# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd096573df40a699fc483b9b5c89885604d36f67b2edecd0fee2f78a2db9e7724999302f2585950123ddfaee6b89b94f78e14834607e8453c02b92ec84da5e5

test:
  secret_key_base: a5828df1226d2e355cb7a15f6a5c662e1238c088e8392f36ea5ff55ff676c71fff648bbb9c608196b2abdc9a0a68b802f68e18c09d3de31e7be30279137c572e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
